# Generated by Django 2.2 on 2019-04-05 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('release_date', models.DateField(null=True)),
                ('users_rating', models.FloatField(null=True)),
                ('users_views', models.IntegerField(null=True)),
                ('critics_rating', models.FloatField(null=True)),
                ('critics_views', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='must',
            name='game_id',
        ),
        migrations.AlterField(
            model_name='must',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('games', models.ManyToManyField(related_name='platforms', to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='api.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('games', models.ManyToManyField(related_name='genres', to='api.Game')),
            ],
        ),
        migrations.AddField(
            model_name='must',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
    ]
