# Generated by Django 2.2 on 2019-04-08 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190405_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.Game'),
        ),
    ]
