# Generated by Django 2.2 on 2019-04-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190408_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-users_rating']},
        ),
    ]
