# Generated by Django 2.2 on 2019-05-02 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190417_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
